language: ruby
rvm:
  - 1.9.3
notifications:
  email: false
  irc:
    channels: "irc.freenode.org#travisstaging"
    template: "[STAGING] %{repository} (%{commit}) %{build_url} : %{message}"
  flowdock: e533e9b0984a1cc7650579ab7aaab158
  hipchat: "a21b28b2863acbee3ccb17da36a173@Travis CI"
  webhooks:
    urls: http://requestb.in/wj5htnwj
    on_start: always
    on_finish: always

script:
#  - bundle exec rspec spec
  - rake

before_script:
  - "echo 'Before script'"
  - "sudo service postgresql restart"

after_script:
  - "echo 'After script'"

after_success:
  - "echo 'After success'"

after_failure:
  - "echo 'After failure'"

after_test:
  - "echo 'Yupi'"
  - "echo 'Splendid'"
  - printenv

env:
  global:
    - secure: "W3U0VAIIvZqj4pNuKrbqdpC0FWELhnMpJZviZsoIayO9pX5ALmntkWSawh5d\nk5+ckAqGroeWkLpHDRC0Cxe0iVNSwunqngnKXMSz98H2Tx5lHv1nM52tALew\nlWmqzNJbaMgnAbUhq7HvV798PM+0Dihqy9ha6yEsFaSvc2G69Ts="
